// Text menus built in the dashboard: the stored shape and every rule the public
// page, the dashboard and the builder share. Kept free of Prisma, React and
// server-only imports so the same rules run in tests and in client components.
// Design: docs/superpowers/specs/2026-10-09-construtor-de-cardapio-design.md

import { z } from "zod";
import { localeForCountry } from "@/i18n/config";
import { FREE_ITEM_LIMIT } from "@/lib/pricing";

export type MenuItem = { id: string; name: string; description?: string; priceCents: number | null };
export type MenuSection = { id: string; title: string | null; items: MenuItem[] };
export type Menu = { v: 1; sections: MenuSection[] };
export type MenuTheme = { logoUrl?: string; color: string; headerStyle: "centered" | "band" };
export type MenuMode = "photos" | "built";

export const MENU_MAX_SECTIONS = 30;
export const MENU_MAX_ITEMS = 300;

// Ids are generated by the builder and used as React keys, so they must be
// short, predictable and unique across the whole menu.
const Id = z.string().regex(/^[a-z0-9_-]{1,32}$/);

const ItemSchema = z.object({
  id: Id,
  name: z.string().trim().min(1).max(80),
  description: z.string().trim().max(200).optional(),
  priceCents: z.number().int().min(0).nullable(),
});

const SectionSchema = z.object({
  id: Id,
  title: z.string().trim().max(60).nullable(),
  items: z.array(ItemSchema),
});

export const MenuSchema: z.ZodType<Menu> = z
  .object({
    v: z.literal(1),
    sections: z.array(SectionSchema).max(MENU_MAX_SECTIONS),
  })
  .superRefine((menu, ctx) => {
    if (countItems(menu) > MENU_MAX_ITEMS) {
      ctx.addIssue({ code: "custom", message: `more than ${MENU_MAX_ITEMS} items` });
    }
    const seen = new Set<string>();
    for (const id of menu.sections.flatMap((s) => [s.id, ...s.items.map((i) => i.id)])) {
      if (seen.has(id)) ctx.addIssue({ code: "custom", message: `duplicate id ${id}` });
      seen.add(id);
    }
  });

export const MenuThemeSchema: z.ZodType<MenuTheme> = z.object({
  logoUrl: z.string().url().optional(),
  color: z.string(),
  headerStyle: z.enum(["centered", "band"]),
});

export const DEFAULT_MENU_THEME: MenuTheme = { color: "#1f2937", headerStyle: "centered" };

export class MenuDataError extends Error {}

// For the public page: a corrupt menu must throw, so a failed ISR regeneration
// keeps serving the last good copy instead of caching an empty one.
export function readPublishedMenu(raw: unknown): Menu | null {
  if (raw == null) return null;
  const parsed = MenuSchema.safeParse(raw);
  if (!parsed.success) throw new MenuDataError(`invalid published menu: ${parsed.error.message}`);
  return parsed.data;
}

// For the dashboard and the funnel: never throws, so bad data can't take them down.
export function publishedItemCount(raw: unknown): number {
  const parsed = MenuSchema.safeParse(raw);
  return parsed.success ? countItems(parsed.data) : 0;
}

export function readMenuTheme(raw: unknown): MenuTheme {
  const parsed = MenuThemeSchema.safeParse(raw);
  return parsed.success ? parsed.data : DEFAULT_MENU_THEME;
}

export function countItems(menu: Menu | null): number {
  return menu ? menu.sections.reduce((n, s) => n + s.items.length, 0) : 0;
}

export function visibleMenu(menu: Menu, pro: boolean): { menu: Menu; hidden: number } {
  if (pro) return { menu, hidden: 0 };
  let left = FREE_ITEM_LIMIT;
  const sections: MenuSection[] = [];
  for (const section of menu.sections) {
    const items = section.items.slice(0, Math.max(left, 0));
    left -= items.length;
    if (items.length > 0) sections.push({ ...section, items });
  }
  return { menu: { ...menu, sections }, hidden: countItems(menu) - countItems({ v: 1, sections }) };
}

export type MenuContent = { menuMode: string; imageCount: number; publishedItemCount: number };

// The mode the public page actually shows. The chosen mode wins when it has
// something to show; otherwise the other one does, so no sequence of clicks
// can blank a menu that has content in either mode.
export function effectiveMode(r: MenuContent): MenuMode {
  const chosen: MenuMode = r.menuMode === "built" ? "built" : "photos";
  const has = (mode: MenuMode) => (mode === "built" ? r.publishedItemCount > 0 : r.imageCount > 0);
  if (has(chosen)) return chosen;
  const other: MenuMode = chosen === "built" ? "photos" : "built";
  return has(other) ? other : "photos";
}

export function isPublished(r: MenuContent): boolean {
  return r.imageCount > 0 || r.publishedItemCount > 0;
}

export const COUNTRY_CURRENCY: Record<string, string> = {
  BR: "BRL",
  PT: "EUR",
  ES: "EUR",
  US: "USD",
  MX: "MXN",
  AR: "ARS",
  UY: "UYU",
  CO: "COP",
  CL: "CLP",
  PE: "PEN",
};

export function currencyForCountry(country: string | null | undefined): string {
  return (country && COUNTRY_CURRENCY[country.toUpperCase()]) || "USD";
}

export function formatPrice(cents: number, country: string | null | undefined): string {
  return new Intl.NumberFormat(localeForCountry(country), {
    style: "currency",
    currency: currencyForCountry(country),
  }).format(cents / 100);
}

function luminance(hex: string): number | null {
  const m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(hex);
  if (!m) return null;
  const full = m[1].length === 3 ? [...m[1]].map((c) => c + c).join("") : m[1];
  const [r, g, b] = [0, 2, 4].map((i) => {
    const c = parseInt(full.slice(i, i + 2), 16) / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

// WCAG AA for large text is 3:1. Below that against the white page, the owner's
// color stays as an accent (rule, band) and titles fall back to a dark tone.
export function headerColors(color: string): { accent: string; title: string } {
  const lum = luminance(color);
  const accent = lum === null ? DEFAULT_MENU_THEME.color : color;
  const contrast = 1.05 / ((lum ?? 0) + 0.05);
  return { accent, title: lum !== null && contrast >= 3 ? color : DEFAULT_MENU_THEME.color };
}

// schema.org Menu for the restaurant's JSON-LD. Callers pass the visible menu
// only, so Google never indexes items the page doesn't show.
export function menuJsonLd(menu: Menu, country: string | null | undefined): Record<string, unknown> {
  const currency = currencyForCountry(country);
  return {
    "@type": "Menu",
    hasMenuSection: menu.sections.map((section) => ({
      "@type": "MenuSection",
      ...(section.title && { name: section.title }),
      hasMenuItem: section.items.map((item) => ({
        "@type": "MenuItem",
        name: item.name,
        ...(item.description && { description: item.description }),
        ...(item.priceCents !== null && {
          offers: { "@type": "Offer", price: (item.priceCents / 100).toFixed(2), priceCurrency: currency },
        }),
      })),
    })),
  };
}
